### ISSUE TITLE
Rescue git history?

### ISSUE THREAD

**Issue by dalito** [adacta-rdm/adacta#13]
Hi Hendrik, I just saw that you killed almost the full history for the public release. 

In case you don't know, it is quite easy to clean the history from commits that should not be disclosed using https://github.com/newren/git-filter-repo - With its help I did some extensive history editing for [voc4cat-tool](https://github.com/nfdi4cat/voc4cat-tool/pull/119) which was surprisingly easy to do.

**Comment by hgossler** [comment]
Hi David,

We had an internal discussion about this and came to the conclusion that the work and time investment to clean the history outweighs the benefits of having it available to the public. Is there something specific you are looking for?

**Comment by dalito** [comment]
I was not looking for something specific. But since I quite often look into the history of my projects (indirectly via blame) to find out what was changed when and by whom, I just wanted to bring the tool to your attention.
