### ISSUE TITLE
Device Table: Long device names in "Currently installed in" get cut off

### ISSUE THREAD

**Issue by jakob-jaegerfeld** [adacta-rdm/adacta#18]
**Describe the bug**
Inside the flat device list, nside the `DeviceTable.tsx` in the "Currently installed in" column, if the name of the parent device is too long, the rendered `DeviceLink` overflows the table cell. 

**To Reproduce**
1. Go to `Devices` -> `Flat List`
2. If the current Repository has a device with a parent device with a name longer than ~155px it will get cut off. Otherwise temporarly try to rename a parent device to a longer name.
4. Inside the "Currently installed in" column, watch the `DeviceLink`  overflow the table cell

**Expected behavior**
Give the `DeviceLink` more horizontal space, and enable propper truncation or let the table cell adjust to the height of the `Device Link` when there is a linke break inside the `Device Link` 

**Screenshots**
No screenshots because of data privacy

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Firefox, probably more(?)
 - Version 0.10.0

**Comment by joeried** [comment]
This was resolved in #15 (IIRC)
